In [23]:
from deepface import DeepFace

image_path = '../data/images_test/CE189/000011.png'
results = DeepFace.extract_faces(img_path=image_path, target_size=(224, 224), detector_backend='retinaface',
                                 enforce_detection=False, align=True)


ValueError: Confirm that ../data/images_test/CE189/000011.png exists

In [72]:
result = results[0]
img = result['face']

In [ ]:
print(result)

In [44]:
import numpy as np

print(img.shape)
print(img.dtype)

(160, 160, 3)
float32


In [73]:
img_uint8 = (img * 255).astype('uint8')
print(img_uint8.shape)
print(img_uint8.dtype)

(224, 224, 3)
uint8


In [74]:
import cv2

cv2.imwrite('./img.jpg', img_uint8)

True

In [75]:
import cv2

rgb_image = cv2.cvtColor(img_uint8, cv2.COLOR_BGR2RGB)
cv2.imwrite('./img.jpg', rgb_image)

True

In [24]:
from deepface import DeepFace

embedding_objs = DeepFace.represent(img_path='./img.jpg', model_name='Facenet', detector_backend='skip',
                                    normalization="Facenet")

In [26]:
print(embedding_objs)

[{'embedding': [-0.5998655557632446, 0.09635789692401886, -0.44526511430740356, -0.5499718189239502, -0.4184122681617737, 1.0316336154937744, -0.047363877296447754, 0.05811057239770889, -0.06364749372005463, -0.4374847412109375, -0.6846475005149841, -0.3969367742538452, -0.667243242263794, -0.3264548182487488, -0.08182108402252197, -1.5358526706695557, 0.4835343360900879, 0.42122185230255127, -0.41429272294044495, -1.7656537294387817, 0.4795822203159332, -0.4724545180797577, -0.08249136805534363, -0.31431305408477783, 0.4089224338531494, -0.1354808509349823, 0.006781302392482758, 1.0812424421310425, -0.1530412882566452, 0.5134035348892212, -0.20185503363609314, 2.0240650177001953, -0.06696172803640366, 0.008617080748081207, 0.6261898875236511, -0.4376049041748047, -0.4781394600868225, -0.8300483822822571, 0.8670490384101868, -1.4367796182632446, -0.3393772840499878, 0.4943060874938965, -0.7407701015472412, -0.5031096339225769, 1.8698087930679321, 0.9831298589706421, 1.0600498914718628,

In [27]:
embedding = embedding_objs[0]["embedding"]
assert isinstance(embedding, list)

In [28]:
len(embedding)

128

In [29]:
print(embedding)

[-0.5998655557632446, 0.09635789692401886, -0.44526511430740356, -0.5499718189239502, -0.4184122681617737, 1.0316336154937744, -0.047363877296447754, 0.05811057239770889, -0.06364749372005463, -0.4374847412109375, -0.6846475005149841, -0.3969367742538452, -0.667243242263794, -0.3264548182487488, -0.08182108402252197, -1.5358526706695557, 0.4835343360900879, 0.42122185230255127, -0.41429272294044495, -1.7656537294387817, 0.4795822203159332, -0.4724545180797577, -0.08249136805534363, -0.31431305408477783, 0.4089224338531494, -0.1354808509349823, 0.006781302392482758, 1.0812424421310425, -0.1530412882566452, 0.5134035348892212, -0.20185503363609314, 2.0240650177001953, -0.06696172803640366, 0.008617080748081207, 0.6261898875236511, -0.4376049041748047, -0.4781394600868225, -0.8300483822822571, 0.8670490384101868, -1.4367796182632446, -0.3393772840499878, 0.4943060874938965, -0.7407701015472412, -0.5031096339225769, 1.8698087930679321, 0.9831298589706421, 1.0600498914718628, -1.65488421916

In [7]:
# Load lại file numpy đã lưu
import numpy as np

npzfile = np.load('../data/embeddings/test_facenet_embeddings.npz')
X = npzfile['embedding']
y = npzfile['label']


In [8]:
print(X[0].shape)

(128,)


In [9]:
print(len(X), len(y))

654 654


In [18]:
import cv2
from numpy import expand_dims
from keras.models import load_model
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
import os

In [14]:
def embedding_vector(model, path_img):
    img = cv2.imread(path_img)
    mean, std = img.mean(), img.std()
    img = (img - mean) / std

    samples = expand_dims(img, axis=0)

    predict = model.predict(samples)

    return predict[0]

In [ ]:
model = load_model('../model/facenet_keras.h5')

In [ ]:
x_train = []
y_train = []
x_test = []
y_test = []

In [ ]:
def get_data(path, x, y):
    image_path = path
    for folder in os.listdir(image_path):
        folder_path = os.path.join(image_path, folder)

        for file in os.listdir(folder_path):
            path_img = os.path.join(folder_path, file)
            emb = embedding_vector(model, path_img)
            x.append(emb)
            y.append(folder)

In [ ]:
get_data(path="../data/faces_train", x=x_train, y=y_train)

In [ ]:
get_data(path="s../data/faces_test", x=x_train, y=y_train)

In [5]:
import numpy as np

train_path = "../data/embeddings/VGG-Face/train_VGG-Face_embeddings.npz"
# Load lại file numpy embeddings
npzfile = np.load(train_path)
X_train = npzfile['embedding']
y_train = npzfile['label']

In [6]:
import numpy as np

test_path = "../data/embeddings/VGG-Face/test_VGG-Face_embeddings.npz"
# Load lại file numpy embeddings
npzfile = np.load(test_path)
X_test = npzfile['embedding']
y_test = npzfile['label']

In [7]:
print(X_train)
print(y_train)
print(len(X_train), len(y_train))

[[-7.40225434e-01 -2.26085186e+00  2.74283625e-03 ... -1.97919440e+00
   5.24204969e+00  9.18417835e+00]
 [ 1.44123626e+00 -2.10662782e-01  5.34805655e-01 ... -1.11319415e-01
   5.14419937e+00  4.94756031e+00]
 [ 7.39432991e-01  8.13351274e-02 -1.92513669e+00 ...  4.39464301e-01
   3.55124402e+00  2.79754472e+00]
 ...
 [ 2.57113838e+00 -2.45878434e+00 -1.59363294e+00 ...  1.36927092e+00
   6.22254848e+00  4.12654257e+00]
 [ 1.45693803e+00 -2.48963428e+00 -1.40273976e+00 ... -4.48384857e+00
   3.51284623e+00  2.51472545e+00]
 [-8.47849399e-02 -1.08674109e+00 -1.09409308e+00 ...  3.19091260e-01
   4.02926254e+00  3.15841722e+00]]
[ 1  1  1 ... 50 50 50]
2104 2104


In [11]:
X_train[0].shape

(2622,)

In [179]:
print(X_test[0], y_test[0])
print(len(X_test), len(y_test))

[ 1.30405784 -2.41341519  1.60164559 ... -2.57689238  5.66663933
  5.73442364] 1
553 553


In [180]:
X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

In [181]:
print(X_train)
print(y_train)
print(len(X_train), len(y_train))

[[-7.40225434e-01 -2.26085186e+00  2.74283625e-03 ... -1.97919440e+00
   5.24204969e+00  9.18417835e+00]
 [ 1.44123626e+00 -2.10662782e-01  5.34805655e-01 ... -1.11319415e-01
   5.14419937e+00  4.94756031e+00]
 [ 7.39432991e-01  8.13351274e-02 -1.92513669e+00 ...  4.39464301e-01
   3.55124402e+00  2.79754472e+00]
 ...
 [ 2.57113838e+00 -2.45878434e+00 -1.59363294e+00 ...  1.36927092e+00
   6.22254848e+00  4.12654257e+00]
 [ 1.45693803e+00 -2.48963428e+00 -1.40273976e+00 ... -4.48384857e+00
   3.51284623e+00  2.51472545e+00]
 [-8.47849399e-02 -1.08674109e+00 -1.09409308e+00 ...  3.19091260e-01
   4.02926254e+00  3.15841722e+00]]
[ 1  1  1 ... 50 50 50]
2104 2104


In [182]:
print(X_test[0], y_test[0])
print(len(X_test), len(y_test))

[ 1.30405784 -2.41341519  1.60164559 ... -2.57689238  5.66663933
  5.73442364] 1
553 553


In [166]:
import cv2
from numpy import expand_dims
from keras.models import load_model
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
import os

In [167]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score

model = SVC(kernel='linear', probability=True)
model.fit(X_train, y_train)
y_pred2 = model.predict(X_test)
cm2 = confusion_matrix(y_test, y_pred2)
ac2 = accuracy_score(y_test, y_pred2)

print(cm2)
print(ac2)

[[13  0  0 ...  0  0  0]
 [ 0 13  0 ...  0  0  0]
 [ 0  0 10 ...  0  0  0]
 ...
 [ 0  0  0 ... 14  0  0]
 [ 0  0  0 ...  0  7  0]
 [ 0  0  0 ...  0  0 12]]
0.9113924050632911


In [168]:
classifier = KNeighborsClassifier(metric="cosine", n_neighbors=3)
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='cosine', n_neighbors=3)

In [169]:
y_pred = classifier.predict(X_test)

In [170]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)

In [171]:
ac

0.8679927667269439

In [172]:
cm

array([[14,  0,  0, ...,  0,  0,  0],
       [ 1, 11,  0, ...,  0,  0,  0],
       [ 0,  0,  9, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 12,  0,  0],
       [ 0,  0,  0, ...,  0,  7,  0],
       [ 0,  0,  0, ...,  0,  0, 12]], dtype=int64)

In [117]:
from deepface import DeepFace

result = DeepFace.verify(img1_path="../data/faces_test/CE001/000002.jpg",
                         img2_path="../data/faces_test/CE001/000025.jpg", model_name="Facenet",
                         distance_metric="cosine", detector_backend="mtcnn")
print(result)


1/1 [==============================] - 0s 25ms/step
{'verified': True, 'distance': 0.21291609269694345, 'threshold': 0.4, 'model': 'Facenet', 'detector_backend': 'mtcnn', 'similarity_metric': 'cosine', 'facial_areas': {'img1': {'x': 37, 'y': 0, 'w': 154, 'h': 216}, 'img2': {'x': 30, 'y': 0, 'w': 157, 'h': 209}}, 'time': 1.45}


In [1]:
from src.extract_features.sift_embeddings import compute_sift_vector, save_embeddings
import cv2

image_path = "../data/faces_test_224/CE001/000002.jpg"

embedding = compute_sift_vector(image_path)

import numpy as np

embedding = np.array(embedding)
print(type(embedding))


<class 'numpy.ndarray'>


In [2]:
print(embedding.shape)

(125, 128)


In [3]:
print((embedding))

[[ 5.  1.  0. ...  0.  0.  3.]
 [26.  0.  0. ...  0. 31. 16.]
 [ 6.  0.  0. ...  1.  0.  1.]
 ...
 [ 1.  1.  0. ...  3.  7. 56.]
 [ 2.  0.  0. ...  0.  0.  0.]
 [ 1.  0.  0. ...  8.  3.  0.]]


In [1]:
from src.extract_features.sift_embeddings import compute_sift_vector, save_sift_embeddings_with_id

save_sift_embeddings_with_id("../data/images_test", "./", "abc.npz")

100%|██████████| 1/1 [00:02<00:00,  2.23s/it]


In [ ]:
from src.utils.load_data import load_data
from src.utils.knn_test import knn

#Facenet
train_path = "./abc.npz"
test_path = "./abc.npz"

x_train, y_train, x_test, y_test = load_data(train_path=train_path, test_path=test_path)
results = knn(x_train, y_train, x_test, y_test)

for k, metrics in results.items():
    print(
        f"k = {k:2d}:  Accuracy: {metrics['accuracy']:.4f}  Precision: {metrics['precision']:.4f}  Recall: {metrics['recall']:.4f}  F1-score: {metrics['f1']:.4f}")

In [3]:
from src.extract_features.sift_embeddings import save_sift_embeddings_with_id

# Trích xuất đặc trưng với SIFT
save_sift_embeddings_with_id("../data/faces_train_224", "../data/embeddings/SIFT", "train_SIFT_embeddings_id.npz")
save_sift_embeddings_with_id("../data/faces_test_224", "../data/embeddings/SIFT", "test_SIFT_embeddings_id.npz")

100%|██████████| 50/50 [00:07<00:00,  6.90it/s]


In [4]:
from src.utils.load_data import load_data
from src.utils.knn_test import knn

#SIFT
train_path = "../data/embeddings/SIFT/train_SIFT_embeddings_id.npz"
test_path = "../data/embeddings/SIFT/test_SIFT_embeddings_id.npz"

x_train, y_train, x_test, y_test = load_data(train_path=train_path, test_path=test_path)
results = knn(x_train, y_train, x_test, y_test)

for k, metrics in results.items():
    print(
        f"k = {k:2d}:  Accuracy: {metrics['accuracy']:.4f}  Precision: {metrics['precision']:.4f}  Recall: {metrics['recall']:.4f}  F1-score: {metrics['f1']:.4f}")

x_train: 2104 y_train: 2104
x_test: 553 y_test: 553
x_train_shape: (16384,)
x_test_shape: (16384,)
k =  1:  Accuracy: 0.0470  Precision: 0.1450  Recall: 0.0470  F1-score: 0.0408
k =  3:  Accuracy: 0.0380  Precision: 0.2459  Recall: 0.0380  F1-score: 0.0319
k =  5:  Accuracy: 0.0434  Precision: 0.1940  Recall: 0.0434  F1-score: 0.0316
k =  7:  Accuracy: 0.0416  Precision: 0.1958  Recall: 0.0416  F1-score: 0.0258
k =  9:  Accuracy: 0.0271  Precision: 0.1860  Recall: 0.0271  F1-score: 0.0167
k = 11:  Accuracy: 0.0271  Precision: 0.2031  Recall: 0.0271  F1-score: 0.0214
